---
name: Add Period Random Times

on:
  schedule:
    # Run twice daily at a base time (UTC)
    - cron: '0 6,18 * * *'  # 6:00 UTC and 18:00 UTC
  workflow_dispatch:  # allow manual runs too

permissions:
  contents: write

jobs:
  edit-file:
    runs-on: ubuntu-latest
    env:
      FILE_PATH: ${{ vars.FILE_PATH || 'file.txt' }}
      COMMIT_NAME: ${{ vars.COMMIT_NAME || github.actor }}
      COMMIT_EMAIL: ${{ vars.COMMIT_EMAIL }}
      COMMIT_MESSAGE: ${{ vars.COMMIT_MESSAGE || 'added period' }}
      GH_PAT: ${{ secrets.GH_PAT }}
      
    steps:
      - name: Random delay before starting
        run: |
          # Delay between 0 and 1800 seconds (0–30 min)
          delay=$(( RANDOM % 1800 ))
          echo "Sleeping for $delay seconds..."
          sleep $delay

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Add period to file
        run: |
          echo -n "." >> "$FILE_PATH"
    
      - name: Commit changes as me
        run: |
          git config user.name "$COMMIT_NAME"
          git config user.email "$COMMIT_EMAIL"
          git add "$FILE_PATH"
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"

      - name: Push with PAT (shows as your account)
        run: |
          git remote set-url origin "https://${GH_PAT}@github.com/${{ github.repository }}.git"
          git push
